name: Run All Playlist Updates (Main Controller)

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  fancode:
    uses: ./.github/workflows/Fancode_update.yml
    secrets: inherit

  tapmad:
    needs: fancode
    if: always()
    uses: ./.github/workflows/Tapmad_bd.yml
    secrets: inherit

  main_combined:
    needs: tapmad
    if: always()
    uses: ./.github/workflows/main_combined.yml
    secrets: inherit
